# Generated by Django 6.1 on 2026-08-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('article_type', models.CharField(max_length=100)),
                ('author_number', models.IntegerField(default=1)),
                ('author_names', models.TextField()),
                ('publication_date', models.DateField()),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(upload_to='submissions_pdfs/')),
                ('indexed_on', models.CharField(max_length=100)),
                ('source_of_funding', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliations', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('indexed', 'Indexed'), ('under_review', 'Under_review'), ('unindexed', 'Unindexed')], default='unindexed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
