# Generated by Django 6.1 on 2026-08-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('indexed', 'Indexed'), ('under_review', 'Under review'), ('unindexed', 'Unindexed')], default='under_review', max_length=20),
        ),
    ]
