# Generated by Django 6.1 on 2026-08-30 08:09

from django.db import migrations, models


def map_old_statuses(apps, schema_editor):
    Submission = apps.get_model('submissions', 'Submission')
    Submission.objects.filter(status='indexed').update(status='reviewed')
    Submission.objects.filter(status='unindexed').update(status='pending')


def undo_map_statuses(apps, schema_editor):
    Submission = apps.get_model('submissions', 'Submission')
    Submission.objects.filter(status='reviewed').update(status='indexed')
    Submission.objects.filter(status='pending').update(status='unindexed')


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_submission_status'),
    ]

    operations = [
        migrations.RunPython(map_old_statuses, undo_map_statuses),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('under_review', 'Under review'),
                    ('reviewed', 'Reviewed'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
    ]
