# Generated by Django 6.1 on 2026-09-08 08:56

import django.core.validators
import submissions.models
from django.conf import settings
from django.core.management import call_command
from django.db import migrations, models


def create_cache_table(apps, schema_editor):
    call_command('createcachetable', verbosity=0)


def drop_cache_table(apps, schema_editor):
    schema_editor.execute('DROP TABLE IF EXISTS portal_cache')


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_review_audit_and_validators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='pdf',
            field=models.FileField(upload_to=submissions.models.pdf_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='submission_status_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['created_at'], name='submission_created_idx'),
        ),
        migrations.RunPython(create_cache_table, drop_cache_table),
    ]
