"""
Django settings for submission_portal project.

Generated by 'django-admin startproject' using Django 6.1.

Deploy values come from environment variables or a gitignored .env file.
Do not put a production SECRET_KEY in this file.
"""

from pathlib import Path
from urllib.parse import unquote, urlparse
import os
import secrets


BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent


def _load_dotenv():
    path = PROJECT_ROOT / '.env'
    if not path.is_file():
        return
    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


def _truthy(name, default='false'):
    return os.environ.get(name, default).strip().lower() in {'1', 'true', 'yes', 'on'}


def _csv(name, default=''):
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


def _secret_key():
    key = os.environ.get('DJANGO_SECRET_KEY', '').strip()
    if key:
        return key
    secret_file = PROJECT_ROOT / '.secret_key'
    if secret_file.is_file():
        stored = secret_file.read_text(encoding='utf-8').strip()
        if stored:
            return stored
    key = secrets.token_urlsafe(50)
    try:
        secret_file.write_text(key + '\n', encoding='utf-8')
    except OSError:
        pass
    return key


def _database():
    url = os.environ.get('DATABASE_URL', '').strip()
    if not url:
        sqlite_path = os.environ.get('SQLITE_PATH', '').strip()
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': Path(sqlite_path) if sqlite_path else BASE_DIR / 'db.sqlite3',
        }
    parsed = urlparse(url)
    scheme = parsed.scheme.split('+')[0]
    if scheme not in {'postgres', 'postgresql'}:
        raise ValueError('DATABASE_URL must be a postgres:// URL or left empty for SQLite.')
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': unquote(parsed.path.lstrip('/')),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port or ''),
    }


_load_dotenv()

SECRET_KEY = _secret_key()
DEBUG = _truthy('DJANGO_DEBUG', 'true')

ALLOWED_HOSTS = _csv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost')
CSRF_TRUSTED_ORIGINS = _csv(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    'http://127.0.0.1:8000,http://localhost:8000',
)

# Empty by default so the visible status URL matches the request host.
PUBLIC_BASE_URL = os.environ.get('PUBLIC_BASE_URL', '').rstrip('/')

LOGIN_URL = 'admin_login'
LOGIN_REDIRECT_URL = 'submission_list'

MAX_PDF_BYTES = 20 * 1024 * 1024
LOGIN_RATE_LIMIT = 5
LOGIN_RATE_WINDOW = 60
STATUS_RATE_LIMIT = 10
STATUS_RATE_WINDOW = 60
DASHBOARD_PAGE_SIZE = 25


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'submissions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'submission_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'submission_portal.wsgi.application'

DATABASES = {
    'default': _database(),
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'submission-portal',
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if _truthy('DJANGO_SECURE_SSL', 'false'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
